name: ee10-autoupdate
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: 'jakartaee-10'
        fetch-depth: '0'
        submodules: 'true'
        token: ${{ secrets.GIT_PASSWORD }}
    - name: Nightly update of JakartaEE 10 modules
      run: |
        git config --global user.email "noreply@piranha.cloud"
        git config --global user.name "Automated workflow"
        git submodule foreach git pull
        git commit -a -m "Nightly update of JakartaEE 10 modules" || true
        git push || true
